<Project>
  <PropertyGroup>
    <RoslynApiVersion>4.14.0</RoslynApiVersion>
  </PropertyGroup>
  <PropertyGroup>
    <BaseIntermediateOutputPath>obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <Import Project="NetEvolve.Defaults.Analyzer.Build.props" />
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
