//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetEvolve.Defaults.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetEvolve.Defaults.Analyzer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;PackageId /&gt; tag. This tag is crucial as it uniquely identifies the package within the project, ensuring proper management and deployment. Without a valid &lt;PackageId /&gt;, the build process may fail, leading to potential issues in package restoration and versioning..
        /// </summary>
        internal static string NED0001Description {
            get {
                return ResourceManager.GetString("NED0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;PackageId /&gt; tag..
        /// </summary>
        internal static string NED0001Message {
            get {
                return ResourceManager.GetString("NED0001Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: &lt;PackageId /&gt; Tag Missing or Incomplete.
        /// </summary>
        internal static string NED0001Title {
            get {
                return ResourceManager.GetString("NED0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;Title /&gt; tag. This tag is essential as it defines the display name of your project, which is used in various contexts, including package management and user interfaces. An incomplete or absent &lt;Title /&gt; can lead to confusion during deployment and may affect how users perceive your project..
        /// </summary>
        internal static string NED0002Description {
            get {
                return ResourceManager.GetString("NED0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;Title /&gt; tag..
        /// </summary>
        internal static string NED0002Message {
            get {
                return ResourceManager.GetString("NED0002Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: &lt;Title /&gt; Tag Missing or Incomplete.
        /// </summary>
        internal static string NED0002Title {
            get {
                return ResourceManager.GetString("NED0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;Description /&gt; tag. This tag is important as it provides a brief overview of your project, helping users and developers understand its purpose and functionality. An incomplete or absent &lt;Description /&gt; can lead to misunderstandings about the project’s goals and may hinder effective collaboration..
        /// </summary>
        internal static string NED0003Description {
            get {
                return ResourceManager.GetString("NED0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;Description /&gt; tag..
        /// </summary>
        internal static string NED0003Message {
            get {
                return ResourceManager.GetString("NED0003Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: &lt;Description /&gt; Tag Missing or Incomplete.
        /// </summary>
        internal static string NED0003Title {
            get {
                return ResourceManager.GetString("NED0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;PackageTags /&gt; tag. This tag is essential for categorizing your package and improving its discoverability in package repositories. Without a properly configured &lt;PackageTags /&gt;, users may find it challenging to locate your project, which can impact its adoption and usage..
        /// </summary>
        internal static string NED0004Description {
            get {
                return ResourceManager.GetString("NED0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;PackageTags /&gt; tag..
        /// </summary>
        internal static string NED0004Message {
            get {
                return ResourceManager.GetString("NED0004Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: &lt;PackageTags /&gt; Tag Missing or Incomplete.
        /// </summary>
        internal static string NED0004Title {
            get {
                return ResourceManager.GetString("NED0004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;PackageProjectUrl /&gt; tag. This tag is vital as it specifies the URL for the project’s homepage or repository, allowing users to easily find more information, documentation, or source code. An incomplete or absent &lt;PackageProjectUrl /&gt; can hinder user engagement and limit the project’s visibility..
        /// </summary>
        internal static string NED0005Description {
            get {
                return ResourceManager.GetString("NED0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;PackageProjectUrl /&gt; tag..
        /// </summary>
        internal static string NED0005Message {
            get {
                return ResourceManager.GetString("NED0005Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: &lt;PackageProjectUrl /&gt; Tag Missing or Incomplete.
        /// </summary>
        internal static string NED0005Title {
            get {
                return ResourceManager.GetString("NED0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;RepositoryUrl /&gt; tag. This tag is crucial as it specifies the URL of the project’s source code repository, enabling users and contributors to access the codebase, report issues, and contribute to development. An incomplete or absent &lt;RepositoryUrl /&gt; can limit collaboration and hinder user engagement..
        /// </summary>
        internal static string NED0006Description {
            get {
                return ResourceManager.GetString("NED0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;RepositoryUrl /&gt; tag..
        /// </summary>
        internal static string NED0006Message {
            get {
                return ResourceManager.GetString("NED0006Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: &lt;RepositoryUrl /&gt; Tag Missing or Incomplete.
        /// </summary>
        internal static string NED0006Title {
            get {
                return ResourceManager.GetString("NED0006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;Authors /&gt; tag. This tag is essential as it specifies the authors of the project, providing credit and context for contributions. An incomplete or absent &lt;Authors /&gt; tag can lead to confusion about authorship and may affect collaboration and recognition within the community..
        /// </summary>
        internal static string NED0007Description {
            get {
                return ResourceManager.GetString("NED0007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;Authors /&gt; tag..
        /// </summary>
        internal static string NED0007Message {
            get {
                return ResourceManager.GetString("NED0007Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: &lt;Authors /&gt; Tag Missing or Incomplete.
        /// </summary>
        internal static string NED0007Title {
            get {
                return ResourceManager.GetString("NED0007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;Company /&gt; tag. This tag is important as it specifies the name of the company or organization responsible for the project. An incomplete or absent &lt;Company /&gt; tag can lead to confusion regarding ownership and may affect branding and recognition in the community..
        /// </summary>
        internal static string NED0008Description {
            get {
                return ResourceManager.GetString("NED0008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is missing or has an incomplete configuration for the &lt;Company /&gt; tag..
        /// </summary>
        internal static string NED0008Message {
            get {
                return ResourceManager.GetString("NED0008Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error: &lt;Company /&gt; Tag Missing or Incomplete.
        /// </summary>
        internal static string NED0008Title {
            get {
                return ResourceManager.GetString("NED0008Title", resourceCulture);
            }
        }
    }
}
