name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/build-dotnet-single.yml@a5609bae17fb2cecd1675150a7382ceae207e5d3 # 2.5.116
    with:
      dotnetLogging: ${{ inputs.dotnet-logging }}
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      solution: ./Defaults.slnx
    secrets: inherit
